### ISSUE TITLE
Point info button was confusing to users

### ISSUE THREAD

**Issue by TheBguy87** [calvin-cs262-fall2021-teamH/Client#59]
Users did not understand the purpose of the point info button.

**Comment by hangrydave** [comment]
Kurt W. added an animation to the point info button to make it more clear that it is a button that can be pressed when near a location. The animation changes the dull grey button to one that flashes between green and grey.

The changes are in this pull request: https://github.com/calvin-cs262-fall2021-teamH/Client/pull/69
